title: Flenser's little TL corner
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://flenser.github.io

color_scheme: dark

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
