title: Flenser Translations
description: Fan translations of various recent and current web novels
theme: just-the-docs

url: https://flenser-tl.nz

color_scheme: dark

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

footer_content: >
  <p>Join the <a href="https://discord.gg/gR9EyGZX8a">Discord</a></p>
  <p>If you'd like to support me for my Kakuyomu subscription, domain registration, etc. You can use my Ko-fi link.
    No obligation, I translate these because I like doing it and I'm not going to paywall any content.
  </p>
  <script type='text/javascript' src='https://storage.ko-fi.com/cdn/widget/Widget_2.js'></script><script type='text/javascript'>kofiwidget2.init('Support me on Ko-fi', '#72a4f2', 'X8X11SY9BQ');kofiwidget2.draw();</script> 
