title: Flenser Translations
description: Fan translations of various recent and current web novels
theme: just-the-docs

url: https://flenser-tl.nz

color_scheme: dark

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
